[package]
name = "piss"
version = "0.1.0"
edition = "2024"

[dependencies]
rayon = { version = "1.10.0", optional = true }

[dev-dependencies]
divan = "0.1.21"

[features]
std = []
rayon = ["std", "dep:rayon"]
